title: sujin shin
description: Front-end web developer
description2: UI developer
site_title: 'sujin's portfolio''

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: sujin91
email: abhishek@nagekar.com

# absolute or relative
profile_picture: assets/my/my.jpeg

# Google Analytics ID
google_analytics: 